INSERT INTO codes VALUES (1, '100', 'MT100');
INSERT INTO codes VALUES (2, '101', 'MT101');
INSERT INTO codes VALUES (3, '103', 'MT103');
INSERT INTO codes VALUES (4, '200', 'MT200');
INSERT INTO codes VALUES (5, '201', 'MT201');
INSERT INTO codes VALUES (6, '202', 'MT202');
INSERT INTO codes VALUES (7, '203', 'MT203');
INSERT INTO codes VALUES (8, 'ADV', 'Separate Advice');
INSERT INTO codes VALUES (9, 'AMD', 'Amendments History');
INSERT INTO codes VALUES (10, 'ATM', 'Cash Withdrawal');
INSERT INTO codes VALUES (11, 'BAC', 'Automated Credit (BAC)');
INSERT INTO codes VALUES (12, 'BAE', 'Branch Acc Entry');
INSERT INTO codes VALUES (13, 'BCA', 'Clean Acceptance');
INSERT INTO codes VALUES (14, 'BCO', 'Non Mkt Close Out');
INSERT INTO codes VALUES (15, 'BCR', 'Clean Reimburse');
INSERT INTO codes VALUES (16, 'BGC', 'Bank Giro Credit');
INSERT INTO codes VALUES (17, 'BGT', 'Guarantees');
INSERT INTO codes VALUES (18, 'BOE', 'Bill of Exchange');
INSERT INTO codes VALUES (19, 'C/L', 'Cashpoint machine');
INSERT INTO codes VALUES (20, 'C/R', 'Credit');
INSERT INTO codes VALUES (21, 'CAE', 'Cheque Collection');
INSERT INTO codes VALUES (22, 'CASH', 'M/C Cash');
INSERT INTO codes VALUES (23, 'CCB', 'Cheque Collection');
INSERT INTO codes VALUES (24, 'CCD', 'Cheque at Despatch');
INSERT INTO codes VALUES (25, 'CHG', 'Charges');
INSERT INTO codes VALUES (26, 'CHP', 'CHAPS Transfer');
INSERT INTO codes VALUES (27, 'CHQ', 'Cheque');
INSERT INTO codes VALUES (28, 'CNA', 'Clean Cheque Neg');
INSERT INTO codes VALUES (29, 'CND', 'Cheque Negotiation');
INSERT INTO codes VALUES (30, 'CRD', 'Card Pymnt or Cash');
INSERT INTO codes VALUES (31, 'D/D', 'Direct Debit');
INSERT INTO codes VALUES (32, 'D/R', 'Debit');
INSERT INTO codes VALUES (33, 'DCR', 'Documentary Credit');
INSERT INTO codes VALUES (34, 'DEBIT', 'M/C Debit');
INSERT INTO codes VALUES (35, 'DFT', 'Foreign Draft');
INSERT INTO codes VALUES (36, 'DIV', 'Dividend');
INSERT INTO codes VALUES (37, 'DPC', 'Unknown');
INSERT INTO codes VALUES (38, 'EBP', 'Bill Payment');
INSERT INTO codes VALUES (39, 'ECA', 'eurocheque');
INSERT INTO codes VALUES (40, 'ECD', 'eurocheque');
INSERT INTO codes VALUES (41, 'ICP', 'Inward Ccy Pymt');
INSERT INTO codes VALUES (42, 'INT', 'Interest');
INSERT INTO codes VALUES (43, 'IP1', 'Inland Payments');
INSERT INTO codes VALUES (44, 'IP2', 'Inland Payments');
INSERT INTO codes VALUES (45, 'IP3', 'Inland Payments');
INSERT INTO codes VALUES (46, 'IP4', 'Inland Payments');
INSERT INTO codes VALUES (47, 'IP5', 'Inland Payments');
INSERT INTO codes VALUES (48, 'IPB', 'Inland Payments');
INSERT INTO codes VALUES (49, 'ISP', 'Inward Stg Pymt');
INSERT INTO codes VALUES (50, 'ITL', 'International Transfer');
INSERT INTO codes VALUES (51, 'ITM', 'Incoming CHAPS');
INSERT INTO codes VALUES (52, 'LON', 'New Loan');
INSERT INTO codes VALUES (53, 'LST', 'Bulk Entry');
INSERT INTO codes VALUES (54, 'LVP', 'Low Value Payment');
INSERT INTO codes VALUES (55, 'MEC', 'Export Credits');
INSERT INTO codes VALUES (56, 'MFD', 'Maturing Fwd Deal');
INSERT INTO codes VALUES (57, 'MGT', 'Bonds & Guarantees');
INSERT INTO codes VALUES (58, 'MIB', 'Inward Bills');
INSERT INTO codes VALUES (59, 'MIC', 'Import Credits');
INSERT INTO codes VALUES (60, 'MKD', 'Market Deal');
INSERT INTO codes VALUES (61, 'MOB', 'Outward Bills');
INSERT INTO codes VALUES (62, 'NDC', 'No Dividend C/foil');
INSERT INTO codes VALUES (63, 'NVD', 'Novated Deal');
INSERT INTO codes VALUES (64, 'OTR', 'OnLine Transaction');
INSERT INTO codes VALUES (65, 'PAYMENT', 'M/C Payment');
INSERT INTO codes VALUES (66, 'POS', 'Point of Sales');
INSERT INTO codes VALUES (67, 'RTF', 'Relay Transfer');
INSERT INTO codes VALUES (68, 'S/O', 'Standing Order');
INSERT INTO codes VALUES (69, 'SALE', 'M/C Sale');
INSERT INTO codes VALUES (70, 'SDE', 'Urgent Euro Tfr');
INSERT INTO codes VALUES (71, 'STF', 'Standard Foreign Transfer');
INSERT INTO codes VALUES (72, 'STL', 'Settlement');
INSERT INTO codes VALUES (73, 'TFP', 'Trade Finance Product');
INSERT INTO codes VALUES (74, 'TFR', 'Transfer');
INSERT INTO codes VALUES (75, 'TLR', 'Card Pymnt or Cash');
INSERT INTO codes VALUES (76, 'U/D', 'Unpaid Direct Debit');
INSERT INTO codes VALUES (77, 'CREDIT', NULL);
INSERT INTO codes VALUES (78, 'Subscription Payment Sent', NULL);
INSERT INTO codes VALUES (79, 'PayPal Express Checkout Payment Sent', NULL);
INSERT INTO codes VALUES (80, 'Web Accept Payment Sent', NULL);
INSERT INTO codes VALUES (81, 'Donation Sent', NULL);
INSERT INTO codes VALUES (82, 'eBay Payment Sent', NULL);
INSERT INTO codes VALUES (83, 'PayPal', NULL);
INSERT INTO codes VALUES (84, 'Payment Sent', NULL);
INSERT INTO codes VALUES (85, 'eBay Payment Received', NULL);
INSERT INTO codes VALUES (86, 'Payment Received', NULL);
INSERT INTO codes VALUES (87, 'Shopping Cart Payment Sent', NULL);
