# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/pydosh.ui'
#
# Created: Thu Jan 10 15:35:55 2013
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_pyDosh(object):
    def setupUi(self, pyDosh):
        pyDosh.setObjectName("pyDosh")
        pyDosh.resize(838, 707)
        self.centralwidget = QtGui.QWidget(pyDosh)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget_3 = QtGui.QWidget(self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_3 = QtGui.QGridLayout(self.widget_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_2 = QtGui.QGroupBox(self.widget_3)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridlayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridlayout.setObjectName("gridlayout")
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridlayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridlayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.gridlayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.dateRangeCheckbox = QtGui.QCheckBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateRangeCheckbox.sizePolicy().hasHeightForWidth())
        self.dateRangeCheckbox.setSizePolicy(sizePolicy)
        self.dateRangeCheckbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dateRangeCheckbox.setText("")
        self.dateRangeCheckbox.setTristate(False)
        self.dateRangeCheckbox.setObjectName("dateRangeCheckbox")
        self.gridlayout.addWidget(self.dateRangeCheckbox, 2, 1, 1, 1)
        self.startDateEdit = QtGui.QDateEdit(self.groupBox_2)
        self.startDateEdit.setObjectName("startDateEdit")
        self.gridlayout.addWidget(self.startDateEdit, 0, 1, 1, 1)
        self.endDateEdit = QtGui.QDateEdit(self.groupBox_2)
        self.endDateEdit.setObjectName("endDateEdit")
        self.gridlayout.addWidget(self.endDateEdit, 1, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.widget_3)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.checkedCombo = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkedCombo.sizePolicy().hasHeightForWidth())
        self.checkedCombo.setSizePolicy(sizePolicy)
        self.checkedCombo.setObjectName("checkedCombo")
        self.gridLayout.addWidget(self.checkedCombo, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.accountCombo = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accountCombo.sizePolicy().hasHeightForWidth())
        self.accountCombo.setSizePolicy(sizePolicy)
        self.accountCombo.setObjectName("accountCombo")
        self.gridLayout.addWidget(self.accountCombo, 1, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.typeCombo = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.typeCombo.sizePolicy().hasHeightForWidth())
        self.typeCombo.setSizePolicy(sizePolicy)
        self.typeCombo.setObjectName("typeCombo")
        self.gridLayout.addWidget(self.typeCombo, 2, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 3, 0, 1, 1)
        self.inoutCombo = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inoutCombo.sizePolicy().hasHeightForWidth())
        self.inoutCombo.setSizePolicy(sizePolicy)
        self.inoutCombo.setObjectName("inoutCombo")
        self.gridLayout.addWidget(self.inoutCombo, 3, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 0, 1, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.widget_3)
        self.groupBox_3.setMinimumSize(QtCore.QSize(320, 0))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_14 = QtGui.QLabel(self.groupBox_3)
        self.label_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 0, 0, 1, 1)
        self.descEdit = SearchLineEdit(self.groupBox_3)
        self.descEdit.setObjectName("descEdit")
        self.gridLayout_2.addWidget(self.descEdit, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.amountEdit = SearchLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.amountEdit.sizePolicy().hasHeightForWidth())
        self.amountEdit.setSizePolicy(sizePolicy)
        self.amountEdit.setObjectName("amountEdit")
        self.gridLayout_2.addWidget(self.amountEdit, 1, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 2, 0, 1, 1)
        self.tagEdit = SearchLineEdit(self.groupBox_3)
        self.tagEdit.setObjectName("tagEdit")
        self.gridLayout_2.addWidget(self.tagEdit, 2, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_3, 0, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(126, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 3, 1, 1)
        self.gridLayout_4.addWidget(self.widget_3, 0, 0, 1, 1)
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.toggleCheckButton = QtGui.QToolButton(self.widget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/accept.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toggleCheckButton.setIcon(icon)
        self.toggleCheckButton.setObjectName("toggleCheckButton")
        self.horizontalLayout_2.addWidget(self.toggleCheckButton)
        self.tagEditButton = QtGui.QToolButton(self.widget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/tag_yellow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tagEditButton.setIcon(icon1)
        self.tagEditButton.setObjectName("tagEditButton")
        self.horizontalLayout_2.addWidget(self.tagEditButton)
        self.reloadButton = QtGui.QToolButton(self.widget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/arrow_refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reloadButton.setIcon(icon2)
        self.reloadButton.setObjectName("reloadButton")
        self.horizontalLayout_2.addWidget(self.reloadButton)
        spacerItem1 = QtGui.QSpacerItem(703, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout_4.addWidget(self.widget, 1, 0, 1, 1)
        self.tableView = QtGui.QTableView(self.centralwidget)
        self.tableView.setObjectName("tableView")
        self.gridLayout_4.addWidget(self.tableView, 2, 0, 1, 1)
        self.widget_2 = QtGui.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.connectionStatusText = QtGui.QLabel(self.widget_2)
        self.connectionStatusText.setObjectName("connectionStatusText")
        self.horizontalLayout_3.addWidget(self.connectionStatusText)
        self.connectionStatusIcon = QtGui.QLabel(self.widget_2)
        self.connectionStatusIcon.setObjectName("connectionStatusIcon")
        self.horizontalLayout_3.addWidget(self.connectionStatusIcon)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.label_10 = QtGui.QLabel(self.widget_2)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)
        self.inTotalLabel = QtGui.QLabel(self.widget_2)
        self.inTotalLabel.setObjectName("inTotalLabel")
        self.horizontalLayout_3.addWidget(self.inTotalLabel)
        spacerItem3 = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.label_11 = QtGui.QLabel(self.widget_2)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.outTotalLabel = QtGui.QLabel(self.widget_2)
        self.outTotalLabel.setObjectName("outTotalLabel")
        self.horizontalLayout_3.addWidget(self.outTotalLabel)
        spacerItem4 = QtGui.QSpacerItem(134, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.label_12 = QtGui.QLabel(self.widget_2)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_3.addWidget(self.label_12)
        self.recordCountLabel = QtGui.QLabel(self.widget_2)
        self.recordCountLabel.setObjectName("recordCountLabel")
        self.horizontalLayout_3.addWidget(self.recordCountLabel)
        self.gridLayout_4.addWidget(self.widget_2, 3, 0, 1, 1)
        pyDosh.setCentralWidget(self.centralwidget)
        self.label_14.setBuddy(self.descEdit)
        self.label_6.setBuddy(self.amountEdit)
        self.label_9.setBuddy(self.tagEdit)

        self.retranslateUi(pyDosh)
        QtCore.QMetaObject.connectSlotsByName(pyDosh)

    def retranslateUi(self, pyDosh):
        pyDosh.setWindowTitle(QtGui.QApplication.translate("pyDosh", "doshLogger", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("pyDosh", "date", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("pyDosh", "start", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("pyDosh", "end", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("pyDosh", "range", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("pyDosh", "filter", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("pyDosh", "checked", None, QtGui.QApplication.UnicodeUTF8))
        self.checkedCombo.setToolTip(QtGui.QApplication.translate("pyDosh", "filter on checked status", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("pyDosh", "account", None, QtGui.QApplication.UnicodeUTF8))
        self.accountCombo.setToolTip(QtGui.QApplication.translate("pyDosh", "filter on account", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("pyDosh", "type", None, QtGui.QApplication.UnicodeUTF8))
        self.typeCombo.setToolTip(QtGui.QApplication.translate("pyDosh", "filter on transaction code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("pyDosh", "in/out", None, QtGui.QApplication.UnicodeUTF8))
        self.inoutCombo.setToolTip(QtGui.QApplication.translate("pyDosh", "filter on transaction code", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("pyDosh", "search", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("pyDosh", "&description", None, QtGui.QApplication.UnicodeUTF8))
        self.descEdit.setToolTip(QtGui.QApplication.translate("pyDosh", "filter by tag", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("pyDosh", "&amount", None, QtGui.QApplication.UnicodeUTF8))
        self.amountEdit.setToolTip(QtGui.QApplication.translate("pyDosh", "filter by amount (Alt-a)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("pyDosh", "&tag", None, QtGui.QApplication.UnicodeUTF8))
        self.tagEdit.setToolTip(QtGui.QApplication.translate("pyDosh", "filter by tag", None, QtGui.QApplication.UnicodeUTF8))
        self.toggleCheckButton.setToolTip(QtGui.QApplication.translate("pyDosh", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\';\">toggle checked (Alt-t)</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.toggleCheckButton.setText(QtGui.QApplication.translate("pyDosh", "&t", None, QtGui.QApplication.UnicodeUTF8))
        self.tagEditButton.setToolTip(QtGui.QApplication.translate("pyDosh", "edit tags (Alt-t)", None, QtGui.QApplication.UnicodeUTF8))
        self.tagEditButton.setText(QtGui.QApplication.translate("pyDosh", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.reloadButton.setToolTip(QtGui.QApplication.translate("pyDosh", "reload data (Alt-r)", None, QtGui.QApplication.UnicodeUTF8))
        self.reloadButton.setText(QtGui.QApplication.translate("pyDosh", "&r", None, QtGui.QApplication.UnicodeUTF8))
        self.connectionStatusText.setText(QtGui.QApplication.translate("pyDosh", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.connectionStatusIcon.setText(QtGui.QApplication.translate("pyDosh", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("pyDosh", "in:", None, QtGui.QApplication.UnicodeUTF8))
        self.inTotalLabel.setToolTip(QtGui.QApplication.translate("pyDosh", "total incoming for filtered records", None, QtGui.QApplication.UnicodeUTF8))
        self.inTotalLabel.setText(QtGui.QApplication.translate("pyDosh", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("pyDosh", "out:", None, QtGui.QApplication.UnicodeUTF8))
        self.outTotalLabel.setToolTip(QtGui.QApplication.translate("pyDosh", "total outgoing for filtered records", None, QtGui.QApplication.UnicodeUTF8))
        self.outTotalLabel.setText(QtGui.QApplication.translate("pyDosh", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("pyDosh", "showing:", None, QtGui.QApplication.UnicodeUTF8))
        self.recordCountLabel.setToolTip(QtGui.QApplication.translate("pyDosh", "filtered records / total records", None, QtGui.QApplication.UnicodeUTF8))
        self.recordCountLabel.setText(QtGui.QApplication.translate("pyDosh", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))

from searchLineEdit import SearchLineEdit
import pydosh_rc
